webtalk_init -webtalk_dir /media/wgx/Ventoy/learn/25spring/computer_org/project/25Spring_CS202_project/CS202_project.sim/sim_1/behav/xsim/xsim.dir/ALU_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May  3 14:00:17 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "431c1766-1e6f-4257-bd1b-56221305ac57" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fb5dcbed9ba74a969c6136a613ee2a84" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "30" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i5-13500H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "406.546 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "90 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "122820_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3180538439 -regid "" -xml /media/wgx/Ventoy/learn/25spring/computer_org/project/25Spring_CS202_project/CS202_project.sim/sim_1/behav/xsim/xsim.dir/ALU_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/wgx/Ventoy/learn/25spring/computer_org/project/25Spring_CS202_project/CS202_project.sim/sim_1/behav/xsim/xsim.dir/ALU_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/wgx/Ventoy/learn/25spring/computer_org/project/25Spring_CS202_project/CS202_project.sim/sim_1/behav/xsim/xsim.dir/ALU_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
