set_property IOSTANDARD LVCMOS33 [get_ports *]


set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN P15 [get_ports reset_n]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N5} [get_ports rx]

set_property PACKAGE_PIN U3 [get_ports {switches1[7]}]
set_property PACKAGE_PIN U2 [get_ports {switches1[6]}]
set_property PACKAGE_PIN V2 [get_ports {switches1[5]}]
set_property PACKAGE_PIN V5 [get_ports {switches1[4]}]
set_property PACKAGE_PIN V4 [get_ports {switches1[3]}]
set_property PACKAGE_PIN R3 [get_ports {switches1[2]}]
set_property PACKAGE_PIN T3 [get_ports {switches1[1]}]
set_property PACKAGE_PIN T5 [get_ports {switches1[0]}]
set_property PACKAGE_PIN P5 [get_ports {switches2[7]}]
set_property PACKAGE_PIN P4 [get_ports {switches2[6]}]
set_property PACKAGE_PIN P3 [get_ports {switches2[5]}]
set_property PACKAGE_PIN P2 [get_ports {switches2[4]}]
set_property PACKAGE_PIN R2 [get_ports {switches2[3]}]
set_property PACKAGE_PIN M4 [get_ports {switches2[2]}]
set_property PACKAGE_PIN N4 [get_ports {switches2[1]}]
set_property PACKAGE_PIN R1 [get_ports {switches2[0]}]

set_property PACKAGE_PIN R15 [get_ports Button_Mid]
set_property PACKAGE_PIN U4 [get_ports Button_Up]

set_property PACKAGE_PIN K1 [get_ports {led1_out[7]}]
set_property PACKAGE_PIN H6 [get_ports {led1_out[6]}]
set_property PACKAGE_PIN H5 [get_ports {led1_out[5]}]
set_property PACKAGE_PIN J5 [get_ports {led1_out[4]}]
set_property PACKAGE_PIN K6 [get_ports {led1_out[3]}]
set_property PACKAGE_PIN L1 [get_ports {led1_out[2]}]
set_property PACKAGE_PIN M1 [get_ports {led1_out[1]}]
set_property PACKAGE_PIN K3 [get_ports {led1_out[0]}]
set_property PACKAGE_PIN F6 [get_ports {led2_out[7]}]
set_property PACKAGE_PIN G4 [get_ports {led2_out[6]}]
set_property PACKAGE_PIN G3 [get_ports {led2_out[5]}]
set_property PACKAGE_PIN J4 [get_ports {led2_out[4]}]
set_property PACKAGE_PIN H4 [get_ports {led2_out[3]}]
set_property PACKAGE_PIN J3 [get_ports {led2_out[2]}]
set_property PACKAGE_PIN J2 [get_ports {led2_out[1]}]
set_property PACKAGE_PIN K2 [get_ports {led2_out[0]}]

set_property PACKAGE_PIN D5 [get_ports {seg1[7]}]
set_property PACKAGE_PIN B2 [get_ports {seg1[6]}]
set_property PACKAGE_PIN B3 [get_ports {seg1[5]}]
set_property PACKAGE_PIN A1 [get_ports {seg1[4]}]
set_property PACKAGE_PIN B1 [get_ports {seg1[3]}]
set_property PACKAGE_PIN A3 [get_ports {seg1[2]}]
set_property PACKAGE_PIN A4 [get_ports {seg1[1]}]
set_property PACKAGE_PIN B4 [get_ports {seg1[0]}]
set_property PACKAGE_PIN H2 [get_ports {seg2[7]}]
set_property PACKAGE_PIN D2 [get_ports {seg2[6]}]
set_property PACKAGE_PIN E2 [get_ports {seg2[5]}]
set_property PACKAGE_PIN F3 [get_ports {seg2[4]}]
set_property PACKAGE_PIN F4 [get_ports {seg2[3]}]
set_property PACKAGE_PIN D3 [get_ports {seg2[2]}]
set_property PACKAGE_PIN E3 [get_ports {seg2[1]}]
set_property PACKAGE_PIN D4 [get_ports {seg2[0]}]
set_property PACKAGE_PIN G2 [get_ports {sel1[3]}]
set_property PACKAGE_PIN C2 [get_ports {sel1[2]}]
set_property PACKAGE_PIN C1 [get_ports {sel1[1]}]
set_property PACKAGE_PIN H1 [get_ports {sel1[0]}]
set_property PACKAGE_PIN G1 [get_ports {sel2[3]}]
set_property PACKAGE_PIN F1 [get_ports {sel2[2]}]
set_property PACKAGE_PIN E1 [get_ports {sel2[1]}]
set_property PACKAGE_PIN G6 [get_ports {sel2[0]}]


